//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assignment1.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        internal static string calculateButton {
            get {
                return ResourceManager.GetString("calculateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID :.
        /// </summary>
        internal static string employeeIdLabel {
            get {
                return ResourceManager.GetString("employeeIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee&apos;s Name :.
        /// </summary>
        internal static string employeeNameLabel {
            get {
                return ResourceManager.GetString("employeeNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string languageGroupBox {
            get {
                return ResourceManager.GetString("languageGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string nextButton {
            get {
                return ResourceManager.GetString("nextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID needs to be entered..
        /// </summary>
        internal static string popupEmployeeIdNeedsToBeEntered {
            get {
                return ResourceManager.GetString("popupEmployeeIdNeedsToBeEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name needs to be entered..
        /// </summary>
        internal static string popupEmployeeNameNeedsToBeEntered {
            get {
                return ResourceManager.GetString("popupEmployeeNameNeedsToBeEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The form you filled up is being sent to the printer..
        /// </summary>
        internal static string popupTheFormYouFilledUpIsBeingSentToThePrinter {
            get {
                return ResourceManager.GetString("popupTheFormYouFilledUpIsBeingSentToThePrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Hours Worked needs to be entered..
        /// </summary>
        internal static string popupTotalHoursWorkedNeedsToBeEntered {
            get {
                return ResourceManager.GetString("popupTotalHoursWorkedNeedsToBeEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Monthly Sales needs to be entered..
        /// </summary>
        internal static string popupTotalMonthlySalesNeedsToBeEntered {
            get {
                return ResourceManager.GetString("popupTotalMonthlySalesNeedsToBeEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to put the positive number..
        /// </summary>
        internal static string popupYouNeedToPutThePositiveNumber {
            get {
                return ResourceManager.GetString("popupYouNeedToPutThePositiveNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should not put more than 160 hours..
        /// </summary>
        internal static string popupYouShouldNotPutMoreThan160Hours {
            get {
                return ResourceManager.GetString("popupYouShouldNotPutMoreThan160Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string printButton {
            get {
                return ResourceManager.GetString("printButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Bonus :.
        /// </summary>
        internal static string salesBonusLabel {
            get {
                return ResourceManager.GetString("salesBonusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Bonus.
        /// </summary>
        internal static string salesBonusThisForm {
            get {
                return ResourceManager.GetString("salesBonusThisForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Hours Worked :.
        /// </summary>
        internal static string totalHoursWorkedLabel {
            get {
                return ResourceManager.GetString("totalHoursWorkedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Monthly Sales :.
        /// </summary>
        internal static string totalMonthlySalesLabel {
            get {
                return ResourceManager.GetString("totalMonthlySalesLabel", resourceCulture);
            }
        }
    }
}
